package coding_challenges.medium;

public class even_fibonacci_sum {
    /*
    Write a method that returns the sum of all even Fibonacci numbers. Consider all Fibonacci numbers that are less than or equal to n.
    Each new element in the Fibonacci sequence is generated by adding the previous two elements.
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    */
    public Integer evenFibonacciSum(Integer n) {
        int fibo_1 = 1, fibo_2 = 2, new_fibo = 0, sum = 2;
        if (1 == n)
            return n;
        if (2 == n)
            return 3;
        do {
            new_fibo = fibo_1 + fibo_2;
            if (new_fibo <= n) {
                fibo_1 = fibo_2;
                fibo_2 = new_fibo;
                if(0==new_fibo%2)
                    sum += new_fibo;
            } else
                return sum;
        } while (true);
    }

    public void go() {
        int[] test_entries = {50,450,1000};
        // expected results: 44, 188, 798
        for (int idx = 0; idx < test_entries.length; idx++) {
            System.out.println("Result for `" + test_entries[idx] + "` is `" + evenFibonacciSum(test_entries[idx]) + "`");
        }
    }
}
